[package]
name = "traw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
serde_json = "1.0.0"
serde = { version = "1.0.0", features = ["derive"] }
cli-clipboard = "0.4.0"
